[16/Jul/2015 10:01:56] WARNING [django.request:170] Not Found: /apple-touch-icon-precomposed.png
[16/Jul/2015 10:01:56] WARNING [django.request:170] Not Found: /apple-touch-icon.png
[16/Jul/2015 10:02:27] ERROR [django.request:256] Internal Server Error: /open/filter/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: pc_computer_labs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/pc/views.py", line 57, in filter_suggestions
    data = sorted(data, key=lambda x: x.get_distance(long1=usr_longitude, lat1=usr_latitude))
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: pc_computer_labs
[20/Jul/2015 08:55:23] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
[20/Jul/2015 08:55:23] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
[20/Jul/2015 08:55:24] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
[20/Jul/2015 08:55:24] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
[20/Jul/2015 08:55:24] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
[20/Jul/2015 08:55:24] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
[20/Jul/2015 10:34:05] WARNING [django.request:170] Not Found: /apple-touch-icon-precomposed.png
[20/Jul/2015 10:34:05] WARNING [django.request:170] Not Found: /apple-touch-icon.png
[20/Jul/2015 15:28:34] ERROR [django.request:256] Internal Server Error: /bookable/filter/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/rooms/views.py", line 121, in filter_suggestions
    data = data.filter(abbreviation=request.GET['building'])
AttributeError: 'list' object has no attribute 'filter'
[21/Jul/2015 14:01:31] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
[21/Jul/2015 14:01:43] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
[21/Jul/2015 14:32:56] ERROR [django.request:256] Internal Server Error: /open/filter/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/pc/views.py", line 51, in filter_suggestions
    building_details=data)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/core/utilities.py", line 122, in sortByDistance
    building_details = sorted(building_details, key=lambda x: get_distance(
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/core/utilities.py", line 123, in <lambda>
    x['longitude'], x['latitude'], long1=usr_longitude, lat1=usr_latitude))
TypeError: 'Computer_Labs' object is not subscriptable
[21/Jul/2015 14:44:01] ERROR [django.request:256] Internal Server Error: /open/filter/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/pc/views.py", line 60, in filter_suggestions
    usr_latitude=usr_latitude)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/core/utilities.py", line 156, in sortingByLocationAndEmptiness
    average_distance = average_distance + pc_lab.get_distance(long1=usr_longitude, lat1=usr_latitude)
AttributeError: 'Computer_Labs' object has no attribute 'get_distance'
[21/Jul/2015 14:59:25] ERROR [django.request:256] Internal Server Error: /open/filter/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/pc/views.py", line 60, in filter_suggestions
    usr_latitude=usr_latitude)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/core/utilities.py", line 173, in sortingByLocationAndEmptiness
    key=lambda x: x.get_heuristic(average_distance, average_ratio, sd_distance, sd_ratio,
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/core/utilities.py", line 174, in <lambda>
    usr_longitude, usr_latitude))
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/pc/models.py", line 82, in get_heuristic
    normalised_distance = (self.get_distance(long, lat) - average_distance) / standard_deviation_distance
AttributeError: 'Computer_Labs' object has no attribute 'get_distance'
[21/Jul/2015 15:00:19] ERROR [django.request:256] Internal Server Error: /open/filter/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/pc/views.py", line 60, in filter_suggestions
    usr_latitude=usr_latitude)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/core/utilities.py", line 173, in sortingByLocationAndEmptiness
    key=lambda x: x.get_heuristic(average_distance, average_ratio, sd_distance, sd_ratio,
TypeError: unorderable types: complex() < complex()
[21/Jul/2015 15:41:59] WARNING [django.request:170] Not Found: /history
[21/Jul/2015 15:41:59] WARNING [django.request:170] Not Found: /favicon.ico
[21/Jul/2015 20:51:15] WARNING [django.request:170] Not Found: /new
[21/Jul/2015 20:51:15] WARNING [django.request:170] Not Found: /favicon.ico
[21/Jul/2015 20:52:49] WARNING [django.request:170] Not Found: /history
[21/Jul/2015 20:53:02] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:03] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:03] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:03] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:04] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:04] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:05] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:06] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:06] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:11] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:13] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:14] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:29] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:30] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:30] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:31] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:32] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:33] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:33] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:35] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:36] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:36] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:36] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:37] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:37] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:38] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:39] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:39] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:44] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:45] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:45] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:46] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:46] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:46] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:46] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:47] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:47] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:47] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:47] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:47] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 147, in like
    user.room_favourites.get(locationId=locationId)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'room_favourites'
[21/Jul/2015 20:53:54] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
[21/Jul/2015 20:55:33] ERROR [django.request:256] Internal Server Error: /new/favourites/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/new/views.py", line 25, in users_favourites
    return render(request, 'new/users/favourites.html', context)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
django.template.base.TemplateDoesNotExist: new/users/favourites.html
[21/Jul/2015 20:55:52] ERROR [django.request:256] Internal Server Error: /new/favourites/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/new/views.py", line 25, in users_favourites
    return render(request, 'new/users/favourites.html', context)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
django.template.base.TemplateDoesNotExist: new/users/favourites.html
[22/Jul/2015 13:49:53] ERROR [django.request:256] Internal Server Error: /like/
Traceback (most recent call last):
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanschristiangregersen/PycharmProjects/InternProject/users/views.py", line 130, in like
    user.pc_favourites.get(id=pc_id)
  File "/Users/hanschristiangregersen/.virtualenvs/booked/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'pc_favourites'
